name: playground

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@5.5.0
        with:
          go-version: "1.20"

      - name: build binary
        run: go build -o main main.go

      - name: run binary
        run: ./main
  windows:
    runs-on: windows-latest
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@5.5.0
        with:
          go-version: "1.20"

      - name: build binary
        run: go build -o main.exe main.go

      - name: run binary
        run: .\main.exe
